### ISSUE TITLE
Zip is BAD

### ISSUE THREAD

**Issue by limelect** [rmesch/Bitmaps2Video#3]
Zip is BAD cannot downLoad OR with FDM download is broken
Reinstall ZIP

**Comment by rmesch** [comment]
Zip downloads, extracts und runs fine here.

**Comment by limelect** [comment]
Sorry not with me plz upload again.
I tried with chrome and FDM not successful

**Comment by rmesch** [comment]
I just uploaded an update, downloaded the master-zip with firefox and edge, it all works as expected. I have neither chrome nor FDM. I suggest to try again without these.

**Comment by limelect** [comment]
OK thanks
P.S I have on my site http://limelect.com/free-programs/
something of a similar nature.
http://limelect.com/downloads/avi2gif-program-decode-avi-into-gif/
It was made with Delphi 20 years ago
