### ISSUE TITLE
How about "TBitmapEncoderM.BitmapToFrameSlow(const bm: TBitmap);" 

### ISSUE THREAD

**Issue by HuichanKIM** [rmesch/Bitmaps2Video#4]
Thank you.

How about this to avoid slow rendering.

procedure TBitmapEncoderM.BitmapToFrameSlow(const bm: TBitmap);
var
  convertCtx: PSwsContext;
  w, h: integer;
  stride: Integer; // Add new var
  ret: integer;
  BitData: TBitmapData;
begin
  if bm.Map(TMapAccess.Read, BitData) then
  begin
    w := bm.Width;
    h := bm.Height;
    stride := BitData.BytesPerLine;

    convertCtx := sws_getContext(w, h,
                                 AV_PIX_FMT_BGRA, //replace of AV_PIX_FMT_BGR24
                                 fWidth, fHeight,
                                 CodecSetup.OutputPixelFormat,
                                 ScaleFunction[fVideoScaling],
                                 nil, nil, nil);
    assert(convertCtx <> nil);

    try
      ret := av_frame_make_writable(yuvpic);
      assert(ret >= 0);
      ret := sws_scale(convertCtx, @BitData.data, @stride, 0, h, @yuvpic.data, @yuvpic.linesize);
      assert(ret >= 0);
    finally
      sws_freeContext(convertCtx);
      bm.Unmap(BitData);
    end;
  end;
end;

**Comment by rmesch** [comment]
Thanks, this looks like what I've been looking for, will integrate it as soon as I'll be able to actually test it under Android, I'm not very familiar with this fmx-stuff yet, haven't even had the hardware until recently. An analog will also simplify the Win-version.
Renate

**Comment by rmesch** [comment]
I have added this to the last release, much appreciated.
