### ISSUE TITLE
Hope to add a sample capture video from USB Camera and save to mp4 file

### ISSUE THREAD

**Issue by dbyoung720** [rmesch/Bitmaps2Video#6]
Hope to add a sample capture video from USB Camera and save to mp4 file.

**Comment by rmesch** [comment]
This class does not support streaming, if that is what you want. If you have the captured video as a file, you can try to create a TBitmapEncoder with a file name *.mp4, add the captured file to it, close and free. If FFmpeg supports the format of the captured video, this should work.
By the way, this is not an issue, for questions like this there is a discussion section.
Good luck!

**Comment by dbyoung720** [comment]
Use DirectShow to get every bitmap image of USB camera video by callback.
Then the bitmap image is encoded as MP4 by TBitmapEncoder. It should be feasible.
